// <auto-generated />
using EngInt2.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace EngInt2.Migrations
{
    [DbContext(typeof(EngInt2Context))]
    [Migration("20200602170927_First")]
    partial class First
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("EngInt2.Models.Comandos", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Desligado");

                    b.Property<int>("Ligado");

                    b.Property<string>("NomeComponente");

                    b.Property<int>("Status");

                    b.Property<int>("Status_Enum");

                    b.HasKey("Id");

                    b.ToTable("Comandos");
                });

            modelBuilder.Entity("EngInt2.Models.SensorTemperaturaUmidade", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Temperatura");

                    b.Property<string>("Umidade");

                    b.HasKey("Id");

                    b.ToTable("SensorTemperaturaUmidade");
                });
#pragma warning restore 612, 618
        }
    }
}
